services:
#  postgres:
#    image: postgres:16-alpine
#    environment:
#      POSTGRES_DB: rocketfin_db
#      POSTGRES_USER: ${USERNAME_DB_ROCKETFIN}
#      POSTGRES_PASSWORD: ${PASSWORD_DB_ROCKETFIN}
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data:
