# ── Database (dev) ────────────────────────────────────────────────────────────
quarkus.hibernate-orm.database.generation=update

# ── Mailer (dev) ──────────────────────────────────────────────────────────────
quarkus.mailer.mock=true
